### PR TITLE
fix: Unknown fields are stripped from WHERE clause (issue #3416)

### PR DESCRIPTION
**Pull request by johannessjoberg**
This fixes the issue for letting through unknown properties in a where clause without a beep.

A potential blocker is that this is considered a breaking change and has already been decided it should be a part of `0.3.0` (https://github.com/typeorm/typeorm/milestone/2) which is long from finished. One possible solution to this could be to use some kind of configuration to let this be introduced without being breaking. I'll investigate more on that tomorrow.

EDIT:

I removed a failing test due to it being based on the faulty functionality.
```
const dbUser = (await userRepo.find({	
    where: {	
        id: Buffer.from(userId, "hex")	
    }	
}))[0];
```
It's querying with a where criteria using the `id` property which does not exist in the `User` model and therefore always returns all users and then selects the first in that array. And the test only sets up one user and it looks like everything is working fine when it's in fact the opposite 🙈

### CODE REVIEW

**Comment by hussfelt** [comment]
NICE! Are we PR'ing this upstream?

**Comment by jalooc** [comment]
Nice job with keeping up with the tests 👍 
One doubt though: this fork, upstream, patch-package in api-manade-models - isn't that too many places to have this same change introduced? Can't we skip this PR and just: 1. make an upstream PR (with this change hidden behind and option flag) and 2. patch-package it in api-manage-models?

**Comment by johannessjoberg** [comment]
Sure thing @jalooc ! I created this fork and PR just for a simple way for us to review this firstly.

**Comment by johannessjoberg** [comment]
Also we need a fork to be able to do a PR towards TORM unless there is another way I'm not aware of? 🤔

**Comment by jalooc** [comment]
> Also we need a fork to be able to do a PR towards TORM unless there is another way I'm not aware of?

Yes we do, but I didn't consider this fork's/PR's purpose end up in the mainstream due to details of our application in the description.

**Pull request closed without merging**
